Create strings.xml
ergoplatform/ergo-wallet-app pull request #95
Opened 2022-03-03 12:02 UTC by ahmetsagirli

Turkish translations of the application were made.

2022-03-03 17:07 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_copy">Koypala</string>
Kopyala

2022-03-03 17:09 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="label_time_span_moments_ago">bir kaç dakika önce</string>
birkaç

2022-03-03 17:15 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="desc_copy_sensitive_data">Lütfen verileri cihaza kopyalayarak pano, üzerine yazmadığınız sürece bu cihazda çalışan her uygulamaya erişebilir pano verileri. Bunu kendi sorumluluğunuz
Verileri cihaz panosuna kopyaladığınızda lütfen dikkatli olun, yeniden üzerine yazmadığınız sürece bu cihazda çalışan her uygulama cihaz panosu verilerine erişebilir. Bunu kendi sorumluluğunuzda yapıyorsunuz.

2022-03-03 17:23 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="title_wallet_balance">Bayiye</string>
Bakiye

2022-03-03 17:26 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="label_to">to</string>
Hedef

2022-03-03 17:29 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="label_send_from">Gönderilecek: %1s</string>
Kaynak

2022-03-03 17:36 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_scan_signed_tx">İmzalı tx'i tara</string>
İmzalı işlemi tara

2022-03-03 17:37 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="error_token_amount">Lütfen geçerli belirteç tutarlarını girin veya geçersiz belirteç girdilerini kaldırın</string>
Lütfen geçerli token tutarlarını girin veya geçersiz token girdilerini kaldırın

2022-03-03 17:38 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="error_request_token_not_found">Belirteç eklenemedi \'%1s\'</string>
Token eklenemedi

2022-03-03 17:39 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="error_request_token_amount">Belirteç için istenen tutar ayarlanamadı \'%1s\'</string>
Token için istenen tutar ayarlanamadı

2022-03-03 18:21 UTC, furkan-gnu requested changes

2022-03-03 18:21 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="error_address_already_added">Adres zaten eklendi \'%1s\'</string>
<string name="error_address_already_added">Adres zaten \'%1s\''a eklendi</string>

* \'%1s\' needs an apostrope -> \'%1s\'('a) -> ex: Adres zaten x'a eklendi

2022-03-03 18:21 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    Bu 15 kelimeyle, buna erişiminizi kaybederseniz cüzdanınızı diğer cihazlara geri yükleyebilirsiniz.\n Tüm 15 kelimeyi (kalem ve kağıtla) dikkatlice yazmanız ve güvenli bir yerde saklamanız çok ön
<string name="intro_create_wallet">Bu senin 15 kelimelik Ergo cüzdan anımsatıcın. Bu kelimeler aynı zamanda bir tohum cümlesi veya kağıt anahtarı olarak da bilinir.
    Bu 15 kelimeyle, bu cüzdana erişiminizi kaybederseniz cüzdanınızı diğer cihazlara geri yükleyebilirsiniz.\n Tüm 15 kelimeyi (kalem ve kağıtla) dikkatlice yazmanız ve güvenli bir yerde saklamanız çok önemlidir.</string>

2022-03-03 18:21 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="check_confirm_create_wallet">Anımsatıcımı güvenli bir yerde saklamaktan sorumlu olduğumu anlıyorum. Eğer bu cihaz üzerinde saklanan anahtarları kayıp edersen, cüzdana ulaşmak için t
<string name="check_confirm_create_wallet">Anımsatıcımı güvenli bir yerde saklamaktan sorumlu olduğumu anlıyorum. Eğer bu cihaz üzerinde saklanan anahtarlar kaybolursa, cüzdanıma erişmenin tek yolu anımsatıcımı kullanmaktır.</string>

2022-03-03 18:21 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="check_confirm_create_wallet">Anımsatıcımı güvenli bir yerde saklamaktan sorumlu olduğumu anlıyorum. Eğer bu cihaz üzerinde saklanan anahtarları kayıp edersen, cüzdana ulaşmak için t
...anahtarlar kaybolursa, cüzdanıma erişmenin tek yolu anımsatıcımı kullanmaktır.

* Added "anımsatıcımı" word (means mnemonic), the phrase will make more sense that way.

2022-03-03 18:21 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="mnemonic_unknown_words">Anımsatıcı geçersiz sözcükler içerir. Yazım hatalarını kontrol et.</string>
<string name="mnemonic_unknown_words">Anımsatıcı geçersiz sözcükler içeriyor. Yazım hatalarını kontrol et.</string>

2022-03-03 19:06 UTC, furkan-gnu requested changes

2022-03-03 19:06 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="label_sign_with">İmzala: %1s (%2s)</string>
<string name="label_sign_with">Şununla imzala: %1s (%2s)</string>

2022-03-03 19:06 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="desc_expert_settings">Uzman Ayarlar</string>
* Uzmanlar için ayarlar (Settings for experts)
* Gelişmiş ayarlar (Advanced settings)

One of these would be better.

2022-03-03 19:06 UTC, furkan-gnu commented on android/src/main/res/values-tr/strings.xml
> +    <string name="label_node_url">Düğüm URL</string>
<string name="label_node_url">Düğüm URL'si</string>

2022-03-03 19:47 UTC, furkan-gnu requested changes
fixed my comments

2022-03-05 16:06 UTC, MrStahlfelge commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_save_password_encrypted">Şifreyi kaydet-şifreli</string>
@root7Z do you have an opinion on this one?

2022-03-05 16:27 UTC, merged

2022-03-05 18:42 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_save_password_encrypted">Şifreyi kaydet-şifreli</string>
I think "Parola ile kimlik doğrulama" is maybe better. In the description it's suggesting to reenter the password every time sending funds

2022-03-05 18:46 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_save_device_encrypted">Cihaza kaydet-şifreli</string>
I think "Cihaz üzerinden kimlik doğrulama" also works, in the description it defines the function. Both works actually but maybe it's better to use same word with the first one :D

2022-03-05 18:50 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_save_device_encrypted">Cihaza kaydet-şifreli</string>
Now I reset the wallet and "Cihazın şifresini kullan" would be more suited with definiton as I understand

2022-03-05 18:51 UTC, root7Z commented on android/src/main/res/values-tr/strings.xml
> +    <string name="button_save_password_encrypted">Şifreyi kaydet-şifreli</string>
And here is the "Cüzdan şifresi oluştur" could be suitable